# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply by two (Rcpp version)
#'
#' This function multiples numbers by two, using C++ code.
#'
#' @param x Numeric vector.
#'
#' @return A numeric vector that is double the input vector
#' @export
timesTwoCpp <- function(x) {
    .Call(`_toyrcpp2_timesTwoCpp`, x)
}

